private_diary/diary/urls.py
from django.urls import path
from . import views

app_name = "diary"
urlpatterns = [
    path("", views.IndexView.as_view(), name = "index"),
    path("inquiry/", views.InquiryView.as_view(), name="inquiry"),
]

private_diary/mystock/urls.py
from django.urls import path
from .views import StockListView, send_notification, refresh_data

app_name = "stock_app"
urlpatterns = [
    path("stock_url/", StockListView.as_view(), name="my_stock_app"),
    path('send-notification/', send_notification, name='send-notification'),
    path('refresh-data/', refresh_data, name='refresh-data'),
]

private_diary/private_diary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('', include('mystock.urls')),
]

private_diary/mystock/models.py
from django.db import models


'''
class MyModelName(models.Model):
    """A typical class defining a model, derived from the Model class."""

    # Fields
    my_field_name = models.CharField(max_length=20, help_text='Enter field documentation')
    ...

    # Metadata
    class Meta:
        ordering = ['-my_field_name']

    # Methods
    def get_absolute_url(self):
            """Returns the url to access a particular instance of MyModelName."""
            return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.field_name
'''
# Create your models here.
class StockModel(models.Model):
    stock_id = models.CharField(
        max_length=10,
        unique=True,
        help_text="stock id ex:00679B"
    )

    name = models.CharField(max_length=20, help_text='Stock name, ex 元大美債20年')

    bid_price = models.FloatField(help_text='bid price')
    price_chage_ratio = models.FloatField(help_text='price chage ratio in %')
    ask_price_first = models.FloatField(help_text='ask (sell) price data 1')
    ask_price_last = models.FloatField(help_text='ask (sell) price data 5')

    buy_price_first = models.FloatField(help_text='buy price data 1')
    buy_price_last = models.FloatField(help_text='buy price data 5')

    high_price = models.FloatField(default=0.0, help_text='open price')
    low_price = models.FloatField(default=0.0,help_text='open price')
    open_price = models.FloatField(help_text='open price')

    date_time = models.DateTimeField()

private_diary/diary/forms.py
import os
from django import forms
from django.core.mail import EmailMessage

class InquiryForm(forms.Form):
    name = forms.CharField(label="姓名", max_length=30)
    email = forms.EmailField(label="信箱")
    title = forms.CharField(label="主旨", max_length=50)
    message = forms.CharField(label="內容", widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["name"].widget.attrs["class"] = "form_control"
        self.fields["name"].widget.attrs["placeholder"] = "請輸入您的姓名"


        self.fields["email"].widget.attrs["class"] = "form_control"
        self.fields["email"].widget.attrs["placeholder"] = "請輸入您的信箱"

        self.fields["title"].widget.attrs["class"] = "form_control"
        self.fields["title"].widget.attrs["placeholder"] = "請輸入信件主旨"

        self.fields["message"].widget.attrs["class"] = "form_control"
        self.fields["message"].widget.attrs["placeholder"] = "請輸入信件內容"

    def send_email(self):
        name = self.cleaned_data["name"]
        email = self.cleaned_data["email"]
        title = self.cleaned_data["title"]
        message = self.cleaned_data["message"]

        subject = "[聯繫我們]{}".format(title)
        message = "寄件者:{}\n信箱:{}\n主旨:{}\n信件內容:{}\n".format(name, email,subject, message)
        from_email = os.environ.get("FROM_EMAIL")
        to_list = [
            os.environ.get("FROM_EMAIL")
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

private_diary/diary/views.py
# Create your views here.

from django.shortcuts import render
from django.views import generic
from .forms import InquiryForm
import logging
from django.urls import reverse_lazy

class IndexView(generic.TemplateView):
    template_name = "index.html"

logger = logging.getLogger(__name__)
class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy("diary:inquiry")

    def form_valid(self, form):
     	  # Handle form submission here (e.g., send email, save to database)
          form.send_email()
          logger.info("Inquiry sent by {}".format(form.cleaned_data["name"]))
          # Redirect to the success URL after processing the form
          return super().form_valid(form)

#    def get_success_url(self):
#     	  # Redirect to a success page or URL after successful form submission
#     	  #return '/success/'
#          return '/'

private_diary/mystock/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import StockModel
from . import stock_query


# Create your views here.
class StockListView(ListView):
  model = StockModel
  #context_object_name = 'my_book_list'   # your own name for the list as a template variable
  template_name = 'stock_list.html'  # Your HTML template

  def get_queryset(self):
    # get data
    # stock_query.py
    stocks_data = stock_query.query()
    # stock_query.stock_2_line()
    for stock_data in stocks_data:
      StockModel.objects.update_or_create(
        stock_id=stock_data.stock_id,
        defaults={
            'name': stock_data.name,
            'bid_price': stock_data.bid,
            'price_chage_ratio': stock_data.cratio,
            'ask_price_first': float(stock_data.ask_list[0]),
            'ask_price_last': float(stock_data.ask_list[-1]),
            'buy_price_first': float(stock_data.buy_list[0]),
            'buy_price_last': float(stock_data.buy_list[-1]),
            'high_price': stock_data.high,
            'low_price': stock_data.low,
            'open_price': stock_data.open,
            'date_time': stock_data.time_str,
        }
    )
    # Return the updated list of books from the database
    return StockModel.objects.all()

# Action for sending Line notification (triggered by the first button)
def send_notification(request):
    stock_query.stock_2_line()
    return redirect('stock_app:my_stock_app')  # Redirect back to the stock list after the action


# Action for refreshing stock data (triggered by the second button)
def refresh_data(request):
    stocks_data = stock_query.query()
    for stock_data in stocks_data:
        StockModel.objects.update_or_create(
            stock_id=stock_data.stock_id,
            defaults={
                'name': stock_data.name,
                'bid_price': stock_data.bid,
                'price_chage_ratio': stock_data.cratio,
                'ask_price_first': float(stock_data.ask_list[0]),
                'ask_price_last': float(stock_data.ask_list[-1]),
                'buy_price_first': float(stock_data.buy_list[0]),
                'buy_price_last': float(stock_data.buy_list[-1]),
                'high_price': stock_data.high,
                'low_price': stock_data.low,
                'open_price': stock_data.open,
                'date_time': stock_data.time_str,
            }
        )
    return redirect('stock_app:my_stock_app')  # Redirect back to the stock list after the action

private_diary/diary/templates/base.html
{% load static %} <!-- 讀取static資料夾內的設定 -->

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title> <!-- 各頁的title自動抓取並添加於此 -->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" /> <!-- 從static資料夾內找到對應位置的圖檔  -->
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" /> <!-- 從static資料夾內找到對應位置的css檔 -->
        <!--My style -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}" />
        {% block head %}{% endblock %} <!-- 各頁的head區塊內容自動抓取並添加於此  -->
    </head>
    <body id="page-top"> <!-- body tag in base.html>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'diary:index' %}"> Start Bootstrap</a> <!-- 本頁網址路徑將參照diary\urls.py的index -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
	                <li class="nav-item"><a class="nav-link" {% block active_mystock %}{% endblock %} href="{% url 'stock_app:my_stock_app' %}">我的自選股</a></li>
	                <li class="nav-item"><a class="nav-link" {% block active_inquiry %}{% endblock %} href="{% url 'diary:inquiry' %}">聯絡我們</a></li>  <!-- 新增此塊區域的程式碼 -->
                    </ul>
                </div>
            </div>
        </nav>
        {% block header %}{% endblock %} <!-- 各頁的header區塊內容自動抓取並添加於此  -->
        {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>  <!-- body end tag in base.html -->
</html>  <!-- end of base.html  -->

private_diary/diary/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}Private Diary{% endblock %}

{% block header %}
<!-- Header-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
	<div class="container px-5">
	    <h1 class="masthead-heading mb-0">Privatey diary</h1>
	    <h2 class="masthead-subheading mb-0">線上個人日記</h2>
	    <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Learn More</a>
	</div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}

<!-- Content section 1 in index.html-->
<section id="scroll">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg' %}" alt="..." /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Web diary</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 2 in index.html-->
<section>
    <div class="container px-5">
	<div class="row gx-5 align-items-center">
	    <div class="col-lg-6">
		<div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg' %}" alt="..." /></div>
	    </div>
	    <div class="col-lg-6">
		<div class="p-5">
		    <h2 class="display-4">Save your diary</h2>
		    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
		</div>
	    </div>
	</div>
    </div>
</section>
{% endblock contents %} <!-- 語法"% endblock [bolckname] %" ;也就是說此處可寫成"% endblock %"或"% endblock contents %" --> 

private_diary/diary/templates/inquiry.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}聯繫我們 | Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}
{% block contents %}
<div class="container">
	<div class="my-div-style">
          <form method="post">
                 {% csrf_token %}

                 {{ form.non_field_errors }}

                 {% for field in form %}
                 <div class="mb-4 col-8">
                      <label for="{{ field.id_for_label }}" class="form-label">
                          <strong>{{ field.label_tag }}</strong>
                     </label>
                     {{ field }}
                     {{ field.errors }}
                 </div>
                 {% endfor %}
               <button class="btn btn-primary" type="submit">送出</button>
           </form>
        </div>
</div>
{% endblock contents %}

private_diary/mystock/templates/stock_list.html
<html>
<head>
<style>
  table{
    border:1px solid #000;
  }
  td{
    border:1px solid #000;
    padding:10px;
  }
</style>
<title>My stock list.html</title>
</head>
<body>
{% if stockmodel_list %}  <!--  the_model_name_list -->
    <table>
      <tr>
        <td>股票名稱</td>
        <td>股票代號</td>
        <td>成交價</td>
        <td>漲跌%</td>
        <td>委買價</td>
        <td>委賣價</td>
        <td>最高價</td>
        <td>最低價</td>
        <td>開盤價</td>
        <td>資料更新時間</td>
      </tr>
      {% for stock in stockmodel_list %}
      <tr>
        <td>{{stock.name}}</td>
        <td>{{stock.stock_id}}</td>
        <td>{{stock.bid_price}}</td>
        <td>{{stock.price_chage_ratio}}</td>
        <td>{{stock.buy_price_first}} - {{stock.buy_price_last}}</td>
        <td>{{stock.ask_price_first}} - {{stock.ask_price_last}}</td>
        <td>{{stock.high_price}}</td>
        <td>{{stock.low_price}}</td>
        <td>{{stock.open_price}}</td>
        <td>{{stock.date_time}}</td>
      </tr>
     {% endfor %}
    </table>
    <ul>
      {% for stock in stockmodel_list %}
      <li>
        ({{stock.name}})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no stock data fetched.</p>
  {% endif %}
  <!-- Button to trigger Line notification -->
  <button type="button" onclick="window.location.href='{% url 'stock_app:send-notification' %}'">Send Notification</button>

  <!-- Button to refresh stock data -->
  <button type="button" onclick="window.location.href='{% url 'stock_app:refresh-data' %}'">Refresh Data</button>

</body>
</html>